export const CONTENT = [
  {
    id: 0,
    coloursDesc: "",
    primaryColor: "",
    secondaryColor: "",
    headerDesc: "",
    header1: "",
    header2: "",
    header3: "",
    header4: "",
    header5: "",
    header6: "",
    bodyDesc: "",
    body: "",
    image1: "",
    image2: "",
    image3: "",
    image4: "",
    image5: "",
    image6: "",
    url: "",
  },
  {
    id: 1,
    coloursDesc: "",
    primaryColor: "",
    secondaryColor: "",
    headerDesc: "",
    header1: "",
    header2: "",
    header3: "",
    header4: "",
    header5: "",
    header6: "",
    bodyDesc: "",
    body: "",
    image1: "",
    image2: "",
    image3: "",
    image4: "",
    image5: "",
    image6: "",
    url: "",
  },
]